version: '3'
services:
  app:
    build: .
    restart: always
    network_mode: host
    volumes:
      - '/zdata/timemachine:/timemachine'
      - '/zdata/share:/share'
      - '/zdata/public:/public'
      - '/etc/localtime:/etc/localtime:ro'
