version: '3'
services:
  app:
    build: .
    restart: always
    network_mode: host
    environment:
      TM_USER: tmbackup
      TM_PW: tmbackup
      TM_SIZE: 1024000
    volumes:
      - '/zdata/timemachine:/timemachine'
      - '/zdata/share:/share'
      - '/zdata/public:/public'
      - '/etc/localtime:/etc/localtime:ro'
