version: '3'
services:
  app:
    build: .
    restart: always
    network_mode: host
    environment:
      TM_USER: timemachine
      TM_PW: timemachine
      TM_SIZE: 512000
    volumes:
      - '/zdata/timemachine:/timemachine'
      - '/zdata/share:/share'
      - '/etc/localtime:/etc/localtime:ro'
